unit uBuiltInConfig;


// This source is distributed under Apache 2.0

// Copyright (C) 2019-2021 Herbert M Sauro

// Author Contact Information:
// email: hsauro@gmail.com


interface

Uses SysUtils, Classes, uLibModule, System.Diagnostics;

const
   RHODUS_VERSION : AnsiString = '3.1.0.0';

type
  TBuiltInConfig= class (TModuleLib)
     procedure   getVersion (vm : TObject);
     procedure   showByteCode (vm : TObject);
     constructor Create;
  end;

implementation

Uses Windows,
    uSymboLTable,
    uVM,
    uStringObject,
    uListObject,
    uHelpUnit,
    uMemoryManager,
    uMachineStack,
    uRhodusEngine;

// --------------------------------------------------------------------------------------------

constructor TBuiltInConfig.Create;
begin
  inherited Create ('config');

  addMethod (getversion, 0, 'version', 'Get the current version number for Rhodus');
  addMethod (showByteCode, 1, 'showByteCode', 'Set tre to show the generated bytecode');

  //path := TListObject.Create(0);
  //path.append(TStringObject.create('.'));
  //path.blockType := btBound;   // To make sure the garbage collector doesn't get it.

  //addListValue ('path', path, 'Search path for Rhodus import libraries', True);
end;


procedure TBuiltInConfig.showByteCode (vm : TObject);
var b : boolean;
begin
   b := TVM (vm).popBoolean;
   TRhodus.bolShowByteCode := b;
   TVM (vm).pushNone;
end;

procedure TBuiltInConfig.getVersion (vm : TObject);
begin
  TVM (vm).push (TStringObject.create(string (RHODUS_VERSION)));
end;



end.
